# comments are to be preserved for easy spinning of configs
services:
  contract:
    #image: i50729/contract:latest
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - leasedb
    #environment:
    # to use if planned to implement cloud-config and service discovery
    #  - contract-service.configserverurl=http://A.B.C.D:8888
    #  - contract-service.eureka.url=http://A.B.C.D:4444/eureka

  leasedb:
    image: mysql:8.3.0
    container_name: leasedb
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      #env_file:
      # - ./mysql/env_vars
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - "80:8080"
    depends_on:
      - leasedb
