version: "3.5"
# comments are to be preserved for easy spinning of configs
services:
  contract:
    #image: i50729/contract:latest
    build: .
#    restart: always
    ports:
      - 8080:8080
    #links:
     # - db:db
    depends_on:
      - db
#    environment:
    # to use if planned to implement cloud-config and service discovery
#      - shopping-service.configserverurl=http://A.B.C.D:8888
#      - shopping-service.eureka.url=http://A.B.C.D:4444/eureka
    networks:
      - appnet
      - dbnet

  db:
    image: mysql:8.0.31
    #container_name: database-server
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./mysql/env_vars
    volumes:
      - db_contract:/var/lib/mysql
    networks:
      - dbnet

  adminer:
    image: adminer
    ports:
      - 80:8080
    networks:
      - appnet
      - dbnet

volumes:
  db_contract:

networks:
  appnet:
    name: appnet
  dbnet:
    name: dbnet

# to implement and use Docker secrets for enhanced security
